/**
 * Module: knowledge
 * Layer: application/dto
 * Purpose: Zod-validated input schemas for Content use cases.
 */

import { z } from "@lib-zod";
import { BLOCK_TYPES } from "../../domain/value-objects/block-content";
import { KNOWLEDGE_PAGE_STATUSES, PAGE_VERIFICATION_STATES } from "../../domain/entities/content-page.entity";

const AccountScopeSchema = z.object({
  accountId: z.string().min(1),
});

export const BlockTypeSchema = z.enum(BLOCK_TYPES);

export const BlockContentSchema = z.object({
  type: BlockTypeSchema,
  text: z.string(),
  properties: z.record(z.string(), z.unknown()).optional(),
});

export type BlockContentDto = z.infer<typeof BlockContentSchema>;

export const CreateKnowledgePageSchema = AccountScopeSchema.extend({
  workspaceId: z.string().min(1).optional(),
  title: z.string().min(1).max(300),
  parentPageId: z.string().min(1).nullable().optional(),
  createdByUserId: z.string().min(1),
});

export type CreateKnowledgePageDto = z.infer<typeof CreateKnowledgePageSchema>;

export const RenameKnowledgePageSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  title: z.string().min(1).max(300),
});

export type RenameKnowledgePageDto = z.infer<typeof RenameKnowledgePageSchema>;

export const MoveKnowledgePageSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  targetParentPageId: z.string().min(1).nullable(),
});

export type MoveKnowledgePageDto = z.infer<typeof MoveKnowledgePageSchema>;

export const ArchiveKnowledgePageSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
});

export type ArchiveKnowledgePageDto = z.infer<typeof ArchiveKnowledgePageSchema>;

export const ReorderKnowledgePageBlocksSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  blockIds: z.array(z.string().min(1)),
});

export type ReorderKnowledgePageBlocksDto = z.infer<typeof ReorderKnowledgePageBlocksSchema>;

export const AddKnowledgeBlockSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  content: BlockContentSchema,
  index: z.number().int().nonnegative().optional(),
});

export type AddKnowledgeBlockDto = z.infer<typeof AddKnowledgeBlockSchema>;

export const UpdateKnowledgeBlockSchema = AccountScopeSchema.extend({
  blockId: z.string().min(1),
  content: BlockContentSchema,
});

export type UpdateKnowledgeBlockDto = z.infer<typeof UpdateKnowledgeBlockSchema>;

export const DeleteKnowledgeBlockSchema = AccountScopeSchema.extend({
  blockId: z.string().min(1),
});

export type DeleteKnowledgeBlockDto = z.infer<typeof DeleteKnowledgeBlockSchema>;

export const CreateKnowledgeVersionSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  label: z.string().max(100).optional(),
  createdByUserId: z.string().min(1),
});

export type CreateKnowledgeVersionDto = z.infer<typeof CreateKnowledgeVersionSchema>;

export const KnowledgePageStatusSchema = z.enum(KNOWLEDGE_PAGE_STATUSES);

// ── Approve content page ──────────────────────────────────────────────────────

export const ExtractedTaskSchema = z.object({
  title: z.string().min(1).max(300),
  dueDate: z.string().optional(),
  description: z.string().optional(),
});

export const ExtractedInvoiceSchema = z.object({
  amount: z.number().positive(),
  description: z.string().min(1),
  currency: z.string().optional(),
});

export const ApproveKnowledgePageSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  actorId: z.string().min(1),
  /**
   * causationId identifies the command (use-case invocation) that caused the
   * resulting event.  Generated by the Server Action layer if not provided by
   * the caller, so that command-event causality is correctly traceable.
   */
  causationId: z.string().min(1).optional(),
  /** Optional: external tasks extracted by AI from this page. */
  extractedTasks: z.array(ExtractedTaskSchema).default([]),
  /** Optional: external invoices extracted by AI from this page. */
  extractedInvoices: z.array(ExtractedInvoiceSchema).default([]),
  /**
   * Correlation ID tracing the entire ingestion → approval → materialization flow.
   * Generated by the caller if not provided (e.g. first action in the flow).
   */
  correlationId: z.string().optional(),
  /** Optional: workspaceId to include in the published event. */
  workspaceId: z.string().optional(),
});

export type ApproveKnowledgePageDto = z.infer<typeof ApproveKnowledgePageSchema>;

// ── Collection DTOs ───────────────────────────────────────────────────────────

export const CollectionColumnTypeSchema = z.enum([
  "text",
  "number",
  "select",
  "multi-select",
  "date",
  "checkbox",
  "url",
  "relation",
]);

export type CollectionColumnTypeDto = z.infer<typeof CollectionColumnTypeSchema>;

export const CollectionColumnInputSchema = z.object({
  name: z.string().min(1).max(100),
  type: CollectionColumnTypeSchema,
  options: z.array(z.string()).optional(),
});

export type CollectionColumnInputDto = z.infer<typeof CollectionColumnInputSchema>;

export const CreateKnowledgeCollectionSchema = AccountScopeSchema.extend({
  workspaceId: z.string().min(1).optional(),
  name: z.string().min(1).max(300),
  description: z.string().max(1000).optional(),
  columns: z.array(CollectionColumnInputSchema).optional(),
  createdByUserId: z.string().min(1),
});

export type CreateKnowledgeCollectionDto = z.infer<typeof CreateKnowledgeCollectionSchema>;

export const RenameKnowledgeCollectionSchema = AccountScopeSchema.extend({
  collectionId: z.string().min(1),
  name: z.string().min(1).max(300),
});

export type RenameKnowledgeCollectionDto = z.infer<typeof RenameKnowledgeCollectionSchema>;

export const AddPageToCollectionSchema = AccountScopeSchema.extend({
  collectionId: z.string().min(1),
  pageId: z.string().min(1),
});

export type AddPageToCollectionDto = z.infer<typeof AddPageToCollectionSchema>;

export const RemovePageFromCollectionSchema = AccountScopeSchema.extend({
  collectionId: z.string().min(1),
  pageId: z.string().min(1),
});

export type RemovePageFromCollectionDto = z.infer<typeof RemovePageFromCollectionSchema>;

export const AddCollectionColumnSchema = AccountScopeSchema.extend({
  collectionId: z.string().min(1),
  column: CollectionColumnInputSchema,
});

export type AddCollectionColumnDto = z.infer<typeof AddCollectionColumnSchema>;

export const ArchiveKnowledgeCollectionSchema = AccountScopeSchema.extend({
  collectionId: z.string().min(1),
});

export type ArchiveKnowledgeCollectionDto = z.infer<typeof ArchiveKnowledgeCollectionSchema>;

// ── Wiki / Knowledge Base DTOs ────────────────────────────────────────────────

export const PageVerificationStateSchema = z.enum(PAGE_VERIFICATION_STATES);

export const VerifyKnowledgePageSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  verifiedByUserId: z.string().min(1),
  /** ISO 8601 — if set, page auto-transitions to "needs_review" after this date. */
  verificationExpiresAtISO: z.string().datetime({ offset: true }).optional(),
});

export type VerifyKnowledgePageDto = z.infer<typeof VerifyKnowledgePageSchema>;

export const RequestPageReviewSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  requestedByUserId: z.string().min(1),
});

export type RequestPageReviewDto = z.infer<typeof RequestPageReviewSchema>;

export const AssignPageOwnerSchema = AccountScopeSchema.extend({
  pageId: z.string().min(1),
  ownerId: z.string().min(1),
  assignedByUserId: z.string().min(1),
});

export type AssignPageOwnerDto = z.infer<typeof AssignPageOwnerSchema>;

export const CreateWikiSpaceSchema = AccountScopeSchema.extend({
  workspaceId: z.string().min(1).optional(),
  name: z.string().min(1).max(300),
  description: z.string().max(1000).optional(),
  createdByUserId: z.string().min(1),
});

export type CreateWikiSpaceDto = z.infer<typeof CreateWikiSpaceSchema>;
