import type { DomainError } from "@/shared/types";

export const SCHEDULE_MDDD_ERROR_CODES = {
  WORKSPACE_REQUIRED: "SCHEDULE_WORKSPACE_REQUIRED",
  REQUIREMENTS_INVALID: "SCHEDULE_REQUIREMENTS_INVALID",
  SLOT_INVALID: "SCHEDULE_SLOT_INVALID",
  REVIEW_OUTCOME_REQUIRED: "SCHEDULE_REVIEW_OUTCOME_REQUIRED",
  MATCH_NOT_FOUND: "SCHEDULE_MATCH_NOT_FOUND",
  MATCH_CANDIDATE_NOT_FOUND: "SCHEDULE_MATCH_CANDIDATE_NOT_FOUND",
  ALLOCATION_REJECTED: "SCHEDULE_ALLOCATION_REJECTED",
  REQUEST_NOT_FOUND: "SCHEDULE_REQUEST_NOT_FOUND",
  REQUEST_REJECT_INVALID: "SCHEDULE_REQUEST_REJECT_INVALID",
  ASSIGNMENT_NOT_FOUND: "SCHEDULE_ASSIGNMENT_NOT_FOUND",
  ASSIGNMENT_REJECT_INVALID: "SCHEDULE_ASSIGNMENT_REJECT_INVALID",
  TASK_NOT_FOUND: "SCHEDULE_TASK_NOT_FOUND",
  SCHEDULE_NOT_FOUND: "SCHEDULE_SCHEDULE_NOT_FOUND",
  SCHEDULE_CANCEL_INVALID: "SCHEDULE_SCHEDULE_CANCEL_INVALID",
  PROJECTION_PERSIST_FAILED: "SCHEDULE_PROJECTION_PERSIST_FAILED",
  REPOSITORY_PERSIST_FAILED: "SCHEDULE_REPOSITORY_PERSIST_FAILED",
  UNEXPECTED_FLOW_ERROR: "SCHEDULE_MDDD_FLOW_FAILED",
  REQUEST_REJECT_FAILED: "SCHEDULE_REQUEST_REJECT_FAILED",
  ASSIGNMENT_REJECT_FAILED: "SCHEDULE_ASSIGNMENT_REJECT_FAILED",
  SCHEDULE_CANCEL_FAILED: "SCHEDULE_CANCEL_FAILED",
} as const;

export type ScheduleMdddErrorCode =
  (typeof SCHEDULE_MDDD_ERROR_CODES)[keyof typeof SCHEDULE_MDDD_ERROR_CODES];

export interface ScheduleMdddDomainError extends DomainError {
  readonly code: ScheduleMdddErrorCode;
  readonly context?: Record<string, unknown>;
}

export function createScheduleMdddDomainError(
  code: ScheduleMdddErrorCode,
  message: string,
  context?: Record<string, unknown>,
): ScheduleMdddDomainError {
  return {
    code,
    message,
    context,
  };
}
